### ISSUE TITLE
Interactive configuration builder - Setup beautifiers, languages, and options

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/assistant#11] opened 2018-03-09 18:07 UTC
**Poll**: Which do you prefer https://clangformat.com/ or http://csscomb.com/config ?

[![](https://api.gh-polls.com/poll/01CEVJB8YQDX7ZRWWD16W33XRS/clangformat)](https://api.gh-polls.com/poll/01CEVJB8YQDX7ZRWWD16W33XRS/clangformat/vote)
[![](https://api.gh-polls.com/poll/01CEVJB8YQDX7ZRWWD16W33XRS/csscomb)](https://api.gh-polls.com/poll/01CEVJB8YQDX7ZRWWD16W33XRS/csscomb/vote)

---

**Must Haves**

- [ ] Display checkbox list of all languages that Unibeautify supports, serves as step 1
- [ ] Generate unique list of options based on all of the languages the user selects
- [ ] Loop through all options, displaying a page for each one
  - [ ] Display box for each value for the option, including a code sample, along with a "don't use this option"
  - [ ] Allow the user to select the value for that option
  - [ ] Show a page for selecting beautifiers?  I kind of feel we need to do this, as some beautifiers you don't have the same amount of control over
- [ ] Generate yaml and json text based on the languages and options the user selected
  - [ ] Ensure options under each language are supported by the language so we don't bloat the file

**Nice to Have**

- [ ] Previous and Next button text should be the name of the page the user is going to next
- [ ] Allow users to download the file directly from the browser

I found CSS Comb's build config flow interesting:  http://csscomb.com/config.

**Comment by szeck87** [comment] 2018-04-06 19:07
@Glavin001 How will Setup Beautifiers work exactly?  Are we going to have the option to select which beautifiers to install versus putting them all in the editor package.json?

**Comment by Glavin001** [comment] 2018-04-06 19:10
I would like to present the user with the supported options for each beautifier. If the user only wants to use a subset of the possible configuration options, then there may be beautifiers which are unnecessary to achieve the desired beautified result and can therefore be removed. Consider the `Options` table for `JavaScript` language: https://unibeautify.com/docs/language-javascript.html#options

I think an interactive tool similar to CSSComb's may allow users to choose "I don't care" for "Choose the code sample you like more:" which would allow us to narrow down which beautifiers we actually need to apply.

Thoughts?

**Comment by szeck87** [comment] 2018-04-06 19:14
OK, so this has nothing to do with the installation of beautifiers themselves?

What would be the difference between Setup Beautifiers and Configuration Beautifiers?

**Comment by Glavin001** [comment] 2018-04-06 19:26
I think the original intent of `Setup Beautifiers` was for resolving error messages like "Could not find XYZ program". The configuration part of the assistant being what we are describing above.

**Comment by szeck87** [comment] 2018-04-14 04:01
I've started working on this.  I'll need some help getting the options pulled in from where ever the source ends up being, and how to best go about "saving" each selected option as they go through the wizard.

[Bootswatch has cards](https://bootswatch.com/lux/) that are perfect for putting code samples in, although I need to figure out how to make them all the same width and height since samples will take up different amounts of whitespace.

![screen shot 2018-04-13 at 10 54 24 pm](https://user-images.githubusercontent.com/8315038/38764123-869803be-3f6e-11e8-858c-e9bfb493badc.png)

**Comment by szeck87** [comment] 2018-04-14 17:05
How I'm approaching it (everything mentioned is under src/pages/setup)  @Glavin001 would like your input on this design and where you would make changes since you know React a lot more than I do.

1. index.tsx serves as the welcome/starting page for configuration.  Probably will have a drop-down for the language users want to configure, which will be passed to the "Wizard" component.

2. The Wizard component creates the base UI for the wizard (buttons for steps, how many steps there are, etc.).  The states I have keeping track here are:

* preStepName: The name of the previous step (in these cases the name of the option), which will be displayed as text in the PREV button
* nexStepName: The name of the next step (in these cases the name of the option), which will be displayed as text in the NEXT button
* stepName: The current step name, to display in the header
* language: The language you are configuring

The wizard will render the base UI, along with OptionButton components.

3. The OptionButton component is each card.  The props that are passed in are "name" for the value of the option in the header and "code" for the sample code in the body.  The language from the Index and Wizard is passed for highlightjs to syntax highlight.

**Comment by Glavin001** [comment] 2018-04-14 18:35
I was thinking:
- Users selects 1 or more languages from list of language checkboxes
- Custom configuration plan is created
- For each option show example
  - Include "I don't care" option so we know which option we can ignore. This allows use to disable beautifiers which support options the user does not care about
  - Use the previous configuration + this new option to generate the example, so it is as personalized for the user as possible (not simply hardcoded option examples)
- Generate configuration file
  - JSON and YAML formats
  - For all languages
  - Only enable beautifiers which are required based on options selected

**Comment by szeck87** [comment] 2018-04-16 01:27
Holding off further until data fetching and beautifying is resolved.

**Comment by Glavin001** [comment] 2018-04-20 20:55
> Holding off further until data fetching and beautifying is resolved.

Sounds like a me thing 😄 . Reassigning.

**Comment by Glavin001** [comment] 2018-04-20 20:56
@szeck87 Do you have a branch you could create as a PR and I will take it over?

**Comment by szeck87** [comment] 2018-04-20 20:58
https://github.com/szeck87/assistant/tree/options-wizard?files=1

I was mostly waiting to decide what to do with the API, whether to have one that there playground and assistant is or one of each.

**Comment by Glavin001** [comment] 2018-04-20 21:30
I think I'll build a reusable API for these public sites. I am still working out how this should function and also be funded.. I want to use Docker and haven't found a free way to run a Docker server 😜 .

**Comment by szeck87** [comment] 2018-05-31 01:26
https://clangformat.com/

**Comment by Glavin001** [comment] 2018-05-31 16:57
@szeck87 Wow that looks great, too!

Which do you prefer https://clangformat.com/ or http://csscomb.com/config ?

**Comment by Glavin001** [comment] 2018-05-31 16:57
/polls new "Which do you prefer?" "https://clangformat.com/" "http://csscomb.com/config"

**Comment by Glavin001** [comment] 2018-05-31 17:05
> Holding off further until data fetching and beautifying is resolved.

@szeck87 New Playground API has been created: https://github.com/Unibeautify/playground/pull/26
It includes support for non-Node.js beautifiers, such as PHP-CS-Fixer.
See https://ntd6xp2n56.execute-api.us-east-1.amazonaws.com/dev/playground/support

**Comment by Glavin001** [comment] 2018-05-31 17:26
@szeck87 you can pass `stdin` like this: https://github.com/Unibeautify/unibeautify/blob/461d80e005ef838e83c5d948bd5b7554681d18e7/test/DependencyManager/ExecutableDependency.spec.ts#L161-L168

**Comment by szeck87** [comment] 2018-05-31 19:40
> Which do you prefer https://clangformat.com/ or http://csscomb.com/config ?

I like the idea of having the options in a list so you can easily go back to one without going through step buttons. And also a description of what the values mean, but that would require an interface change in Unibeautify.  However it lacks a real builder where you can select something and are able to download the config file itself.

I think a hybrid would look/function well.  First and last steps are always "Select Languages" and "Finish" or something, where the latter would have the config file available for download.  Once the languages are selected, the left pane would list out all of the options based on them.  The rest would look something like https://github.com/Unibeautify/assistant/issues/11#issuecomment-381301455.  I don't know if the code toggle like clang-format has there would work all of the time, depending on how many values are there for an option.  It certainly looks better than the boxes from csscomb and ours.

**Comment by Glavin001** [comment] 2018-06-05 07:01
@szeck87 Here's what I have so far:

![image](https://user-images.githubusercontent.com/1885333/40959956-a3dfe994-6874-11e8-92d8-825fe3d9a339.png)

![image](https://user-images.githubusercontent.com/1885333/40959991-bc43039a-6874-11e8-97f0-c3dde234d9fb.png)

![image](https://user-images.githubusercontent.com/1885333/40960038-e5d04f42-6874-11e8-94ff-3824abcca4c4.png)

![image](https://user-images.githubusercontent.com/1885333/40960047-ea3a9164-6874-11e8-843a-a5a3d1efc167.png)

Now we need real examples for each of the languages.

I think you suggested earlier putting all of the examples into a separate and central repository and then including it into Website and Assistant? Would you be able to work on that and finish off this PR? 😃

**Comment by Glavin001** [comment] 2018-06-08 14:38
@szeck87 : Thoughts on adding analytics to the process? We could track how long it takes a user to complete X number of options choices and then calculate an average. Then later we could say "you have Y steps with X options to choose, it usually takes someone Z minutes to complete"

**Comment by Glavin001** [comment] 2018-06-08 14:40
We could detect whether the beautified samples are actually unique. If they are not, we could add a button to say "Report a problem" or something, since the samples do not demonstrate how the option will change the code.
 
![image](https://user-images.githubusercontent.com/1885333/41164084-b2f60262-6b10-11e8-831f-a76e49472319.png)

**Comment by szeck87** [comment] 2018-06-08 15:01
Yea I like both of those ideas.  Give users the ability to report that there are issues with the steps, and at the same time we can track.  Can we track how much time a user spends on a specific option?

I also think we don't need the Add/Edit example buttons here.  Maybe a link in the metadata that says `More Info` and links to the unibeautify.com page for that option, where it has the buttons?

**Comment by Glavin001** [comment] 2018-06-08 15:27
> Can we track how much time a user spends on a specific option?

We can track anything we can measure (in milliseconds) and send to Google Analytics with https://developers.google.com/analytics/devguides/collection/gtagjs/user-timings

So we could track a step page, such as `10. Align Assignments` which has 4 languages and they spend X milliseconds on it. 👍 

> I also think we don't need the Add/Edit example buttons here. Maybe a link in the metadata that says More Info and links to the unibeautify.com page for that option, where it has the buttons?

I really want to encourage users via the website and now here in the assistant to contribute. If the sample does not demonstrate properly, change it! If there is no sample, add one! I want to leverage the power of the open-source community as much as possible.

**Comment by Glavin001** [comment] 2018-06-08 15:30
While playing around with the assistant I found a problem.

I reproduced it in the Playground:
- [Bad](https://playground.unibeautify.com/#N4IgNghgdg5grhGBTAchAtkkAuEAVATwAckBlAYwCcBLIgFxABoQB7e6lqAZx1AGEAxLxAAjJBDh1qAM2pJKPbAG0QABUpI6dAgAIAIjOkgAugF9mfUqWFiJU2fMUr1mqfKZqNW3QelHmAFKkALQAQuKSMgQm5iB8LGAAJgBicFwcUDYR9nIKOM5e2vqGMcwAokFZdjK5Tp6uPiWBIeHV0tFmzADilBBEABYAigAyVZEOecr1WrmlIAASeACyo9igtuO1+dNFvv4gQWHZUXOLKwDUZQBKoWM5jtsu3sV+p9CJYEgiEJPrxxN1J67JoHFr-DqxIIAeRQdxqDymQNmzCBjVezSObQhzQAGnCAY9Csidmj9odWuNsQcIAA3CD4raIwqkuYBWkQCg0egMhEFVyzYzMIi9GDoCAAfWo3HkDGw0ggYC4SGYAHdekRxWApUhNUhYHR+jgABwABiFIrF4o0AEc4NQNDh5YrlSA9YlxSrqAbxUr0NRyAlODg6JQ4C7bSw6EhFCAoJwsMwpYk9XQfdQAF5YbAAJkTUGTUFTXG0nxwIC4RAg5ATIB+lBYKvFlY03DLCpVEAIPGYLBEACskORU+Q4JQwAQfZXyFKYMHQy6+1wAB7ikS9cgAa00iidSuYbo9Xv64oD6DFjoVe5ASZTJ5YZ5TihDYeYa-EG5P-Qg2vdmANLESHdLxdMUV2FaN5BpHUoCQFUtRgxQAEYzXLKcdQgaQo0ocVoE4cVpDgKAhwyC9nWYdA4DAKR4J1LCoB+aJcHbTtu1rLUYCgHCuHSDjMELICyNEdcdWLAhS1wAMwEgIglQ8cClUoKDxRguDtSfedmEIm9C0-b8YN-TR+gAgSrwrKsdSlJsfj1UjTLQyVOKQdB6AnZsbLlYDmEXeDUy-IgiEY3cXS3JANTrTsHILOgICkIMPMEszq1XJBpBYDQ73zL0MgVOcXxAQjo3IPoRJDGcTJdA9PW9FSaNsl1T0tWQFFlIK8yi3Sf3FP8jMA3KXQ0dAWCUkNv3gmAPX6L1ozQurYmGaNFD+NpGT5GZ3BRZkXiMToQGGahbWoRIeUmFRyXBOYlh+DdEgbTI1lEf4Vp2AVYiWNJovIfosyWzZeVBTFKTmVR5lUY7ARB4JLGCZJqCXdwdquDhZR++4TpJLa5lISxrHujZUcBIl1vRvZMYANS6MHCQaDGdtICBuMpplqZJ2m0O+X4HuWv7URp2JSE9Wdcce7nNpZ2I8C9aBqDgdAdFIEskDlr7t0Z1bgVeHa8AF1XiZKTXiDIKhaGRznfrRpEiZ5lnzUQS0pQUlrPJANU+k1bVdX1Q1sFNG3RQlG07QdeKr0qo8fSc-1Azu1qQAjKMYzjGCPG0osMyzXNr3zW9RPE1DzI8OsGyslsY2YrsPF7AchxPUdx0nKsZz6rzl1Xdctzocr93zQ9vQa+lg5dFO7wffim6E98Ov0rrDOMuryIgMCNAUpSarUnBkOYRL0Mw+QcMT-DCOIuKY4oqjqBo8U6IYtswA7cvmAVagOK4nioD4jvZuYUnqC4BAwFSyg1YdZWz1rEUmYZgGE0oHMHEKxIHMxBGdLEMC8BOSIJAKM8Dnhi1iGlJ+UoFSoKXLKEABEiKxSgDoagwwhpIFJvIAgNDYBXEIlCKAqRyEcDQJgLgAAKMAnAYAAEFKAwEQjobAOhiw0FgIwHQuEDTyBETACROgoAyzEJQORdAWAsEulAAgyiuCqJELoz40AACUOhgAAB1KE6AcQGbgCQkAADoBEwF4TYkA3iLEAG47GmDsXYkApggA)
- [Good](https://playground.unibeautify.com/#N4IgNghgdg5grhGBTAchAtkkAuEAVATwAckBlAYwCcBLIgFxABoQB7e6lqAZx1AGEAxLxAAjJBDh1qAM2pJKPbAG0QABUpI6dAgAIAIjOkgAugF9mfUqWFiJU2fMUr1mqfKZqNW3QelHmAFKkALQAQuKSMgQm5iB8LGAAJgBicFwcUDYR9nIKOM5e2vqGMcwAokFZdjK5Tp6uPiWBIeHV0tFmzADilBBEABYAigAyVZEOecr1WrmlIAASeACyo9igtuO1+dNFvv4gQWHZUXOLKwDUZQBKoWM5jtsu3sV+p9CJYEgiEJPrxxN1J67JoHFr-DqxIIAeRQdxqDymQNmzCBjVezSObQhzQAGnCAY9Csidmj9odWuNsQcIAA3CD4raIwqkuYBWkQCg0egMhEFVyzYzMIi9GDoCAAfWo3HkDGw0ggYC4SGYAHdekRxWApUhNUhYHR+jgABwABiFIrF4o0AEc4NQNDh5YrlSA9YlxSrqAbxUr0NRyAlODg6JQ4C7bSw6EhFCAoJwsMwpYk9XQfdQAF5YbAAJkTUGTUFTXG0nxwIC4RAg5ATIB+lBYKvFlY03DLCpVEAIPGYLBEACskORU+Q4JQwAQfZXyFKYMHQy6+1wAB7ikS9cgAa00iidSuYbo9Xv64oD6DFjoVe5ASZTJ5YZ5TihDYeYa-EG5P-Qg2vdmANLESHdLxdMUV2FaN5BpHUoCQFUtRgxQAEYzXLKcdQgaQo0ocVoE4cVpDgKAhwyC9nWYdA4DAKR4J1LCoB+aJcHbTtu1rLUYCgHCuHSDjMELICyNEdcdWLAhS1wAMwEgIglQ8cClUoKDxRguDtSfedmEIm9C0-b8YN-TR+gAgSrwrKsdSlJsfj1UjTLQyVOKQdB6AnZsbLlYDmEXeDUy-IgiEY3cXS3JANTrTsHILOgICkIMPMEszq1XJBpBYDQ73zL0MgVOcXxAQjo3IPoRJDGcTJdA9PW9FSaNsl1T0tWQFFlIK8yi3Sf3FP8jMA3KXQ0dAWCUkNv3gmAPX6L1ozQurYmGaNFD+NpGT5GZ3BRZkXiMToQGGahbWoRIeUmFRyXBOYlh+DdEgbTI1lEf4Vp2AVYiWNJovIfosyWzZeVBTFKTmVR5lUY7ARB4JLGCZJqCXdwdquDhZR++4TpJLa5lISxrHujZUcBIl1vRvZMYANS6MHCQaDGdtICBuMpplqZJ2m0O+X4HuWv7URp2JSE9Wdcce7nNpZ2I8C9aBqDgdAdFIEskDlr7t0Z1bgVeHa8AF1XiZKTXiDIKhaGRznfrRpF4fNRBLSlBSWs8kA1T6TVtV1fVDWwU0rdFCUbTtB14qvSqjx9Jz-UDO7WpACMoxjOMYI8bSiwzLNc2vfNb1E8TUPMjw6wbKyWxjZiuw8XsByHE9R3HScqxnPqvOXVd1y3Ohyv3fND29Br6UDl0k7vB9+IboT3w6-SusM4y6vIiAwI0BSlJqtScGQ5hEvQzD5Bw+P8MI4i4qjiiqOoGjxTohi2zADtS+YBVqA4rieKgPi29m5hSeoLgEDAVLKGrHWPMxYfzDIAwmlA5g4hWGA5mIIzpYkgXgJyRBIBRhgc8MWsQ0oPylAqJBS5ZQgAIkRWKUAdDUGGENJApN5AEEobAK4hEoRQFSCQjgaBMBcAABRgE4DAAAgpQGAiEdDYB0MWGgsBGA6FwgaeQgiYCiJ0FAGWYhKDSLoCwFgl0oAEAUVwJRIgtGfGgAASh0MAAAOmQnQtiAzcASEgAAdLwmAXDLEgA8aYgA3NY0w1jrEgFMEAA)

Currently all beautifiers are enabled in some arbitrary order. We need to provide tools so users know cases like this "If you care about option X, then Prettier respects it and Pretty Diff messes it up. You want Prettier to be before Pretty Diff." 🤔

**Comment by szeck87** [comment] 2018-06-08 15:40
> Currently all beautifiers are enabled in some arbitrary order. We need to provide tools so users know cases like this "If you care about option X, then Prettier respects it and Pretty Diff messes it up. You want Prettier to be before Pretty Diff."

Sort of goes back to one of the Must Haves:  "Show a page for selecting beautifiers? I kind of feel we need to do this, as some beautifiers you don't have the same amount of control over"

Beautifiers like Prettier don't support many options and even override what other beautifiers do since it's opinionated.  How does the pipeline work exactly?  Does it go through one beautifier first, then the next, and so on?  If Prettier is always the last, very little of how you configure Unibeautify might be used.

**Comment by Glavin001** [comment] 2018-06-09 03:49
> How does the pipeline work exactly? Does it go through one beautifier first, then the next, and so on?

Yes, exactly. `beautifiers: ["A", "B", "C"]` goes in order of the items in the array. This works great if you know what you are doing. Not great for beginners, who may be very surprised when a beautifier wipes out their formatting from previous beautifier.

>  If Prettier is always the last, very little of how you configure Unibeautify might be used.

Very true.

---

One idea is to order by importance. For example, if you have options A, B, C configured and each are supported by a different beautifier, you could apply the beautifiers in reverse order -- the most important being last. For example, this could mean Prettier (opinionated) first and ESLint (configurable) second, which is what https://github.com/prettier/prettier-eslint does. 🤔

**Closed** 2018-06-17 15:13 UTC
Labels: enhancement, help wanted
